name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: |
        echo ${{ secrets.dockerhub_pat }} | docker login -u lubishtanid --password-stdin
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag argocd-testing:$(date +%s)

    - uses: actions/checkout@v3
    - name: Push Docker Image
      run: docker push lubishtanid/argocd-testing:$(date +%s)
